version: '3'
services:
  app:
    container_name: express-mongo
    restart: always
    build: ./
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    links:
      - mongo
    environment:
      - NODE_ENV=docker

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
